apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AazadD/devops-infra.git
    targetRevision: main
    path: helm/app-chart
    helm:
      values: |
        replicaCount: 1
        image:
          repository: hawatharu/devops-app
          tag: "staging-latest"
          pullPolicy: Always
        environment: staging
        ingress:
          enabled: true
          host: staging.app.local
        autoscaling:
          enabled: false
        pdb:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
